//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.12 at 10:05:15 AM CST 
//


package com.dardo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeEnhancersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeEnhancersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="memoryBonus" type="{http://dardo.com/eve-api/characterSheet}AttributeBonusType"/>
 *         &lt;element name="willpowerBonus" type="{http://dardo.com/eve-api/characterSheet}AttributeBonusType"/>
 *         &lt;element name="perceptionBonus" type="{http://dardo.com/eve-api/characterSheet}AttributeBonusType"/>
 *         &lt;element name="intelligenceBonus" type="{http://dardo.com/eve-api/characterSheet}AttributeBonusType"/>
 *         &lt;element name="charismaBonus" type="{http://dardo.com/eve-api/characterSheet}AttributeBonusType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeEnhancersType", propOrder = {
    "memoryBonus",
    "willpowerBonus",
    "perceptionBonus",
    "intelligenceBonus",
    "charismaBonus"
})
public class AttributeEnhancersType {

    @XmlElement
    protected AttributeBonusType memoryBonus;
    @XmlElement
    protected AttributeBonusType willpowerBonus;
    @XmlElement
    protected AttributeBonusType perceptionBonus;
    @XmlElement
    protected AttributeBonusType intelligenceBonus;
    @XmlElement
    protected AttributeBonusType charismaBonus;

    /**
     * Gets the value of the memoryBonus property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBonusType }
     *     
     */
    public AttributeBonusType getMemoryBonus() {
        return memoryBonus;
    }

    /**
     * Sets the value of the memoryBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBonusType }
     *     
     */
    public void setMemoryBonus(AttributeBonusType value) {
        this.memoryBonus = value;
    }

    /**
     * Gets the value of the willpowerBonus property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBonusType }
     *     
     */
    public AttributeBonusType getWillpowerBonus() {
        return willpowerBonus;
    }

    /**
     * Sets the value of the willpowerBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBonusType }
     *     
     */
    public void setWillpowerBonus(AttributeBonusType value) {
        this.willpowerBonus = value;
    }

    /**
     * Gets the value of the perceptionBonus property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBonusType }
     *     
     */
    public AttributeBonusType getPerceptionBonus() {
        return perceptionBonus;
    }

    /**
     * Sets the value of the perceptionBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBonusType }
     *     
     */
    public void setPerceptionBonus(AttributeBonusType value) {
        this.perceptionBonus = value;
    }

    /**
     * Gets the value of the intelligenceBonus property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBonusType }
     *     
     */
    public AttributeBonusType getIntelligenceBonus() {
        return intelligenceBonus;
    }

    /**
     * Sets the value of the intelligenceBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBonusType }
     *     
     */
    public void setIntelligenceBonus(AttributeBonusType value) {
        this.intelligenceBonus = value;
    }

    /**
     * Gets the value of the charismaBonus property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeBonusType }
     *     
     */
    public AttributeBonusType getCharismaBonus() {
        return charismaBonus;
    }

    /**
     * Sets the value of the charismaBonus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeBonusType }
     *     
     */
    public void setCharismaBonus(AttributeBonusType value) {
        this.charismaBonus = value;
    }

}
