//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.12 at 10:05:15 AM CST 
//


package com.dardo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeBonusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeBonusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="augmentatorName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="augmentatorValue" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeBonusType", propOrder = {
    "augmentatorName",
    "augmentatorValue"
})
public class AttributeBonusType {

    @XmlElement
    protected String augmentatorName;
    @XmlElement
    protected int augmentatorValue;

    /**
     * Gets the value of the augmentatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAugmentatorName() {
        return augmentatorName;
    }

    /**
     * Sets the value of the augmentatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAugmentatorName(String value) {
        this.augmentatorName = value;
    }

    /**
     * Gets the value of the augmentatorValue property.
     * 
     */
    public int getAugmentatorValue() {
        return augmentatorValue;
    }

    /**
     * Sets the value of the augmentatorValue property.
     * 
     */
    public void setAugmentatorValue(int value) {
        this.augmentatorValue = value;
    }

}
