//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.12 at 10:05:15 AM CST 
//


package com.dardo.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="intelligence" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="charisma" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="perception" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="willpower" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributesType", propOrder = {
    "intelligence",
    "memory",
    "charisma",
    "perception",
    "willpower"
})
public class AttributesType {

    @XmlElement
    protected int intelligence;
    @XmlElement
    protected int memory;
    @XmlElement
    protected int charisma;
    @XmlElement
    protected int perception;
    @XmlElement
    protected int willpower;

    /**
     * Gets the value of the intelligence property.
     * 
     */
    public int getIntelligence() {
        return intelligence;
    }

    /**
     * Sets the value of the intelligence property.
     * 
     */
    public void setIntelligence(int value) {
        this.intelligence = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     */
    public int getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     */
    public void setMemory(int value) {
        this.memory = value;
    }

    /**
     * Gets the value of the charisma property.
     * 
     */
    public int getCharisma() {
        return charisma;
    }

    /**
     * Sets the value of the charisma property.
     * 
     */
    public void setCharisma(int value) {
        this.charisma = value;
    }

    /**
     * Gets the value of the perception property.
     * 
     */
    public int getPerception() {
        return perception;
    }

    /**
     * Sets the value of the perception property.
     * 
     */
    public void setPerception(int value) {
        this.perception = value;
    }

    /**
     * Gets the value of the willpower property.
     * 
     */
    public int getWillpower() {
        return willpower;
    }

    /**
     * Sets the value of the willpower property.
     * 
     */
    public void setWillpower(int value) {
        this.willpower = value;
    }

}
