//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.12 at 10:05:15 AM CST 
//


package com.dardo.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterSheetResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterSheetResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="characterID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="race" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bloodline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="corporationName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="corporationID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="allianceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="allianceID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cloneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cloneSkillPoints" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="balance" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="attributeEnhancers" type="{http://dardo.com/eve-api/characterSheet}AttributeEnhancersType"/>
 *         &lt;element name="attributes" type="{http://dardo.com/eve-api/characterSheet}AttributesType"/>
 *         &lt;element name="rowset" type="{http://dardo.com/eve-api/characterSheet}CharacterSheetRowsetType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterSheetResultType", namespace = "http://dardo.com/eve-api/characterSheet", propOrder = {
    "characterID",
    "name",
    "race",
    "bloodline",
    "gender",
    "corporationName",
    "corporationID",
    "allianceName",
    "allianceID",
    "cloneName",
    "cloneSkillPoints",
    "balance",
    "attributeEnhancers",
    "attributes",
    "rowset"
})
public class CharacterSheetResultType {

    @XmlElement
    protected String characterID;
    @XmlElement
    protected String name;
    @XmlElement
    protected String race;
    @XmlElement
    protected String bloodline;
    @XmlElement
    protected String gender;
    @XmlElement
    protected String corporationName;
    @XmlElement
    protected int corporationID;
    @XmlElement
    protected String allianceName;
    @XmlElement
    protected int allianceID;
    @XmlElement
    protected String cloneName;
    @XmlElement
    protected int cloneSkillPoints;
    @XmlElement
    protected BigDecimal balance;
    @XmlElement
    protected AttributeEnhancersType attributeEnhancers;
    @XmlElement
    protected AttributesType attributes;
    @XmlElement
    protected List<CharacterSheetRowsetType> rowset;

    /**
     * Gets the value of the characterID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacterID() {
        return characterID;
    }

    /**
     * Sets the value of the characterID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacterID(String value) {
        this.characterID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the race property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRace() {
        return race;
    }

    /**
     * Sets the value of the race property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRace(String value) {
        this.race = value;
    }

    /**
     * Gets the value of the bloodline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBloodline() {
        return bloodline;
    }

    /**
     * Sets the value of the bloodline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBloodline(String value) {
        this.bloodline = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the corporationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorporationName() {
        return corporationName;
    }

    /**
     * Sets the value of the corporationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorporationName(String value) {
        this.corporationName = value;
    }

    /**
     * Gets the value of the corporationID property.
     * 
     */
    public int getCorporationID() {
        return corporationID;
    }

    /**
     * Sets the value of the corporationID property.
     * 
     */
    public void setCorporationID(int value) {
        this.corporationID = value;
    }

    /**
     * Gets the value of the allianceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllianceName() {
        return allianceName;
    }

    /**
     * Sets the value of the allianceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllianceName(String value) {
        this.allianceName = value;
    }

    /**
     * Gets the value of the allianceID property.
     * 
     */
    public int getAllianceID() {
        return allianceID;
    }

    /**
     * Sets the value of the allianceID property.
     * 
     */
    public void setAllianceID(int value) {
        this.allianceID = value;
    }

    /**
     * Gets the value of the cloneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloneName() {
        return cloneName;
    }

    /**
     * Sets the value of the cloneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloneName(String value) {
        this.cloneName = value;
    }

    /**
     * Gets the value of the cloneSkillPoints property.
     * 
     */
    public int getCloneSkillPoints() {
        return cloneSkillPoints;
    }

    /**
     * Sets the value of the cloneSkillPoints property.
     * 
     */
    public void setCloneSkillPoints(int value) {
        this.cloneSkillPoints = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBalance(BigDecimal value) {
        this.balance = value;
    }

    /**
     * Gets the value of the attributeEnhancers property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeEnhancersType }
     *     
     */
    public AttributeEnhancersType getAttributeEnhancers() {
        return attributeEnhancers;
    }

    /**
     * Sets the value of the attributeEnhancers property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeEnhancersType }
     *     
     */
    public void setAttributeEnhancers(AttributeEnhancersType value) {
        this.attributeEnhancers = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link AttributesType }
     *     
     */
    public AttributesType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributesType }
     *     
     */
    public void setAttributes(AttributesType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the rowset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rowset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRowset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharacterSheetRowsetType }
     * 
     * 
     */
    public List<CharacterSheetRowsetType> getRowset() {
        if (rowset == null) {
            rowset = new ArrayList<CharacterSheetRowsetType>();
        }
        return this.rowset;
    }

}
